# Generated by Django 5.1 on 2024-08-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ENT', 'Entertainment'), ('SPT', 'Sports'), ('NEW', 'News'), ('OTH', 'Other')], default='OTH', max_length=4)),
                ('text', models.TextField(max_length='240')),
            ],
        ),
    ]
