# Generated by Django 5.1 on 2024-08-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_tweettype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweettype',
            name='text',
            field=models.CharField(max_length=240),
        ),
    ]
