# Generated by Django 5.1 on 2024-08-24 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0003_alter_tweettype_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweettype',
            name='text',
        ),
    ]
