# Generated by Django 5.1 on 2024-08-24 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0004_remove_tweettype_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tweet.tweettype'),
        ),
    ]
