# Generated by Django 5.1 on 2024-08-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0008_tweetinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetinfo',
            name='tweetTagsSplitForm',
            field=models.JSONField(default=list),
        ),
    ]
